package project_3;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Article {
	private final String title;
	private final String description;
	private final String url;
	private final String publishedAt;
	
	@JsonIgnoreProperties({"status", "source", "author", "urlToImage", "content"})
	
	
	@JsonCreator Article(@JsonProperty("title") String title, @JsonProperty("description") String description,
			@JsonProperty("url") String url, @JsonProperty("publishedAt") String publishedAt) {
		this.title = title;
		this.description = description;
		this.url = url;
		this.publishedAt = publishedAt;
	}
	
	/* Returns an integer value, generated by a hashing algorithm
	 * @param None
	 * @return an integer representing the hash value
	 * */
	@Override
	public int hashCode() {
		return Objects.hash(description, publishedAt, title, url);
	}
	
	/* Compares two object based on their contents
	 * @param obj - an Object to be compared with
	 * @return boolean - representing whether the two objects are equal
	 * */
	@Override
	public boolean equals(Object obj) {
		
		if (obj == this) {
			return true;
		}
		if (obj == null)
			return false;
		if (!(obj instanceof Article)) {
			return false;
		}
		Article a1 = (Article) obj;
		return this.title.equals(a1.title) && this.description.equals(a1.description) && this.url.equals(a1.url)
				&& this.publishedAt.equals(a1.publishedAt);
	}


	public String getTitle() {
		return title;
	}

	public String getDescription() {
		return description;
	}

	public String getUrl() {
		return url;
	}


	public String getPublishedAt() {
		return publishedAt;
	}
	

}
